pipeline {
    agent any
    
    tools{
        maven "maven 3.6.1"
    }
    
    stages {
        stage("build"){
            steps {
                dir("worker"){
                    sh 'ls -ltr'
                    sh 'mvn compile'
                }
            }
        }
        stage("test"){
            steps {
                dir("worker"){
                    sh 'mvn clean test'
                }
            }
        }
        stage('package') {
            steps {
                dir("worker"){
                   sh 'mvn package -DskipTests'
                   achiveArtifacts artifacts: '**/target/*.jar'
                }
            }
        }
    }
}
